Some ehancements
GitOrigin-RevId: ccc8c4a2e33ff640998c27b43e8d401d4c2cde0f

diff --git a/infrastructure/services/remote/php-fpm/populate_elasticsearch_index b/infrastructure/services/remote/php-fpm/populate_elasticsearch_index
--- a/infrastructure/services/remote/php-fpm/populate_elasticsearch_index
+++ b/infrastructure/services/remote/php-fpm/populate_elasticsearch_index
@@ -1,14 +1,18 @@
 #!/bin/bash
 
+echo "Checking if elasticsearch is booted..."
 while ! curl http://localhost:9200 > /dev/null 2>&1;
   do sleep 0.1
+  echo "Waiting for elasticsearch to boot..."
 done
+echo "Elasticsearch is up"
 
-su capco -c "php bin/console capco:es:create --env=prod --no-interaction --quiet"
+su capco -c "php bin/console capco:es:create --env=prod --no-interaction"
 # Increasing memory_limit is required when importing a lot of content
-su capco -c "php -d memory_limit=512m bin/console capco:es:populate --env=prod --no-interaction --quiet"
+su capco -c "php -d memory_limit=512m bin/console capco:es:populate --env=prod --no-interaction"
 
 if [ $? -eq 1 ]; then
+  echo "Populating the index failed... Exiting" >&2
   exit 1
 fi
 
