Update populate_elasticsearch_index
fix typo

GitOrigin-RevId: 7d9f5535bc8999a8eecac1ab694b3e150f8ef333

diff --git a/infrastructure/services/remote/php-fpm/run b/infrastructure/services/remote/php-fpm/run
--- a/infrastructure/services/remote/php-fpm/run
+++ b/infrastructure/services/remote/php-fpm/run
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+start=$SECONDS
+
 echo "Configuring New Relic..."
 sed -i 's/newrelic.appname = ""/newrelic.appname = '"$NR_INSTALL_NAME"'/' /etc/php5/*/conf.d/20-newrelic.ini
 sed -i 's/newrelic.license = ""/newrelic.license = '"$NR_INSTALL_KEY"'/' /etc/php5/*/conf.d/20-newrelic.ini
@@ -8,49 +10,53 @@ cd /var/www
 
 for directory in app/cache app/logs web/bundles; do
   if [ ! -d "$directory" ]; then
-    echo "Creating '$directory' ..."
+    echo "Creating '$directory'..."
     mkdir -p -m 777 $directory
   fi
 done
 
-echo "Checking media permissions..."
+echo "Checking media permissions after $(( SECONDS - start )) seconds..."
 chmod -R 777 web/media
 
-echo "Clearing previous cache..."
-rm -rf app/cache/*
+echo "Warming up cache and install bundle assets after $(( SECONDS - start )) seconds..."
+su capco <<'EOF'
+cd /var/www
+php app/console cache:warmup --no-debug --no-optional-warmers --env=prod --no-interaction
+php app/console assets:install --symlink --env=prod --no-interaction
+EOF
 
-echo "Checking if mysql is booted..."
+echo "Checking if mysql is booted after $(( SECONDS - start )) seconds..."
 while ! mysql --host=127.0.0.1 > /dev/null 2>&1;
   do sleep 1
   echo "Waiting mysql to boot..."
 done
-echo "Mysql is up"
+echo "Mysql is ready after $(( SECONDS - start )) seconds!"
 
-su capco <<'EOF'
-
-cd /var/www
-
-RESULT=`php app/console doctrine:migrations:status --env=prod 2>&1 | grep -o "Unknown database" | wc -l`
-if [ "$RESULT" != "0" ]; then
+VERSIONS=`php app/console doctrine:migrations:status --show-versions --env=prod --no-interaction 2>&1`
+database=`echo "$VERSIONS" | grep -o "Unknown database" | wc -l`
+if [ "$database" != "0" ]; then
     echo "Creating a new database with base data..."
-    php app/console doctrine:database:create --if-not-exists --env=prod --no-interaction
+    php app/console doctrine:database:create --env=prod --no-interaction
     php app/console doctrine:schema:create --env=prod --no-interaction
     php app/console doctrine:migrations:version --add --all --env=prod --no-interaction
     php app/console capco:load-base-data --force --env=prod --no-interaction
 else
+  migrations=`echo "$VERSIONS" | grep -o "not migrated" | wc -l`
+  if [ "$migrations" == "0" ]; then
+      echo "No migrations to execute."
+  else
     echo "Migrating an existing database..."
     php app/console doctrine:migrations:migrate --env=prod --no-interaction
+    if [ $? -eq 1 ]; then
+      echo "Database migration failed... Exiting" >&2
+      exit 1
+    fi
+  fi
 fi
+echo "Database is ready after $(( SECONDS - start )) seconds!"
 
-php app/console cache:warmup --env=prod --no-interaction
-php app/console assets:install --symlink --env=prod --no-interaction
+echo "Starting daemon to populate elasticsearch..."
+/etc/service/php-fpm/populate_elasticsearch_index &
 
-echo "Checking if elasticsearch is booted..."
-while ! curl http://localhost:9200 > /dev/null 2>&1; do sleep 1; done
-
-echo "Elasticsearch has booted - Starting a daemon to populate the index."
-php app/console fos:elastica:populate --env=prod --no-interaction &
-
-EOF
-
+echo "php-fpm is ready to boot after $(( SECONDS - start )) seconds!"
 exec php5-fpm -y /etc/service/php-fpm/fpm.conf -O
