elasticsearch populate daemon
GitOrigin-RevId: 55aba698185d916333e169d01b0b3150e0eb00e5

diff --git a/infrastructure/services/remote/php-fpm/run b/infrastructure/services/remote/php-fpm/run
--- a/infrastructure/services/remote/php-fpm/run
+++ b/infrastructure/services/remote/php-fpm/run
@@ -26,10 +26,6 @@ while ! mysql --host=127.0.0.1 > /dev/null 2>&1;
 done
 echo "Mysql is up"
 
-su capco <<'EOF'
-
-cd /var/www
-
 RESULT=`php app/console doctrine:migrations:status --env=prod 2>&1 | grep -o "Unknown database" | wc -l`
 if [ "$RESULT" != "0" ]; then
     echo "Creating a new database with base data..."
@@ -40,17 +36,17 @@ if [ "$RESULT" != "0" ]; then
 else
     echo "Migrating an existing database..."
     php app/console doctrine:migrations:migrate --env=prod --no-interaction
+    if [ $? -eq 1 ]; then
+      echo "Database migration failed... Exiting" >&2
+      exit 1
+    fi
 fi
+echo "Done !"
 
 php app/console cache:warmup --env=prod --no-interaction
 php app/console assets:install --symlink --env=prod --no-interaction
 
-echo "Checking if elasticsearch is booted..."
-while ! curl http://localhost:9200 > /dev/null 2>&1; do sleep 1; done
-
-echo "Elasticsearch has booted - Starting a daemon to populate the index."
-php app/console fos:elastica:populate --env=prod --no-interaction &
-
-EOF
+echo "Starting daemon to populate elasticsearch..."
+./etc/service/php-fpm/populate_elasticsearch_index &
 
 exec php5-fpm -y /etc/service/php-fpm/fpm.conf -O
