update rabbitmq external server vhost (#14432)
GitOrigin-RevId: 68d245b4f4f97eb5b2c6a5b54ced7f2e0e239b14

diff --git a/infrastructure/services/remote/php-fpm/run b/infrastructure/services/remote/php-fpm/run
--- a/infrastructure/services/remote/php-fpm/run
+++ b/infrastructure/services/remote/php-fpm/run
@@ -63,7 +63,18 @@ else
 
     echo "[$(date -u)][PHP-FPM] Updating RabbitMQ vhost to match schema..."
     gosu capco php bin/rabbit vhost:mapping:create --host=${SYMFONY_RABBITMQ_HOST:-127.0.0.1} --vhost=${SYMFONY_RABBITMQ_VHOST:-capco}  --user=${SYMFONY_RABBITMQ_LOGIN:-guest} --password=${SYMFONY_RABBITMQ_PASSWORD:-guest} config/rabbitmq.yaml --quiet
-    echo "[$(date -u)][PHP-FPM] RabbitMQ vhost updated!"
+    
+    RESULT=$?
+    if [ $RESULT -eq 0 ]; then
+        echo "[$(date -u)][PHP-FPM] RabbitMQ vhost updated!"
+    else
+        echo "[$(date -u)][PHP-FPM] RabbitMQ vhost update failed because it did not exist yet."
+
+        echo "[$(date -u)][PHP-FPM] Creating RabbitMQ vhost schema..."
+        gosu capco php bin/rabbit vhost:mapping:create --host=${SYMFONY_RABBITMQ_HOST:-127.0.0.1} --vhost=${SYMFONY_RABBITMQ_VHOST:-capco}  --user=${SYMFONY_RABBITMQ_LOGIN:-guest} --password=${SYMFONY_RABBITMQ_PASSWORD:-guest} config/rabbitmq.yaml --erase-vhost --quiet
+        echo "[$(date -u)][PHP-FPM] RabbitMQ vhost created!"
+    fi
+    
 fi
 
 echo "[$(date -u)][PHP-FPM] Warming up cache and install bundle assets..."
